default: &default
  adapter: mysql2
  pool: 5

development:
  <<: *default
  database: todomvc_development

test:
  <<: *default
  database: todomvc_test

production:
  <<: *default
  database: todomvc_production
